
export const theme = {
    token: {
        colorPrimary: '#3F72AF',
        colorSecondary: '#DBE2EF',
        colorSuccess: '#2a9d8f',
        colorWarning: '#f77f00',
        colorError: '#d62828',
        fontFamily: 'Roboto',
        colorBorder: '#F5F7FB',
    },
    components: {
        Form: {
            verticalLabelPadding: '0',
        },
        Table: {
            rowExpandedBg: '#F5F7FB',
            headerBg: '#DBE2EF',
            headerColor: '#555',
            rowHoverBg: '#DBE2EF99',
        },
        Collapse: {
            contentPadding: '20px',
            headerPadding: '10px',
            contentBg: '#F5F7FB',
        },
        Menu: {
            itemColor: '#3F72AF',
            itemBg: '#112D4E',
            itemSelectedColor: '#DBE2EF',
            itemSelectedBg: '#112D4E',
            itemHoverColor: '#DBE2EF',
            itemHoverBg: '#3F72AF',
            itemDisabledColor: '#555',
            darkItemColor: '#3F72AF',
            darkItemBg: '#112D4E',
            darkItemSelectedColor: '#DBE2EF',
            darkItemSelectedBg: '#112D4E',
            darkItemHoverColor: '#DBE2EF',
            darkItemHoverBg: '#3F72AF',
            darkItemDisabledColor: '#555',
            itemMarginBlock: '0',
            itemMarginInline: '20px',
            iconMarginInlineEnd: '20px',
            activeBarBorderWidth: '0',
            groupTitleColor: '#3F72AF',
            darkGroupTitleColor: '#3F72AF',
            darkSubMenuItemBg: '#112D4E',
            popupBg: '#112D4E',
            motion: 'false',
        },
        Tabs: {
            itemActiveColor: '#3F72AF',
            itemColor: '#777',
            itemHoverColor: '#3F72AF',
            itemSelectedColor: '#555',
            cardBg: 'rgb(0,0,0,200)',
            horizontalItemPadding: '8px 20px',
        },
        Layout: {
            bodyBg: '#F5F7FB',
            headerBg: '#F5F7FB', //#f5f5f5;
            headerHeight: 40,
            headerPadding: '0 40px',
            siderBg: '#112D4E',
            footerBg: '#F5F7FB',
            footerPadding: '10px 0',
        },
        Modal: {
            contentBg: '#ffffff',
            headerBg: '#F5F7FB',
            footerBg: '#F5F7FB',
            titleColor: '#3F72AF',
            titleFontSize: 24,
        },
    },
};
