
export const theme = {
    token: {
        colorPrimary: '#2277BB',
        colorLink: '#2277BB',
        colorInfo: '#2277BB',
        colorInfoText: '#2277BB',
        colorInfoTextActive: '#2277BB',
        colorLinkActive: '#2277BB',
        colorSuccess: '#52c41a',
        colorWarning: '#33AADD',
        colorError: '#f5222d',
        fontSize: 14,
        fontFamily: 'Roboto',
        colorTextHeading: 'rgba(0, 0, 0, 0.85)',
        colorTextBase: 'rgba(0, 0, 0, 0.65)',
        colorTextSecondary: 'rgba(0, 0, 0, 0.45)',
        colorTextDisabled: 'rgba(0, 0, 0, 0.7)',
        colorBgContainerDisabled: 'rgba(0, 0, 0, 0.03)',
        borderRadius: 2,
        colorBorder: '#d9d9d9',
        verticalLabelPadding: '0',
    },
    components: {
        Form: {
            verticalLabelPadding: '0',
        },
        Table: {
            rowExpandedBg: '#e9e5e0',
            headerBg: '#555',
            headerColor: '#555',
            rowHoverBg: '#2277BB19',
        },
        Collapse: {
            contentPadding: '20px',
            headerPadding: '10px',
            contentBg: '#f5f3f0',
        },
        Menu: {
            itemColor: '#bbb',
            itemBg: '#373533',
            itemSelectedColor: '#33AADD',
            itemSelectedBg: '#373533',
            itemHoverColor: '#bbb',
            itemHoverBg: '#33AADD77',
            itemDisabledColor: '#555',
            darkItemColor: '#bbb',
            darkItemBg: '#373533',
            darkItemSelectedColor: '#33AADD',
            darkItemSelectedBg: '#373533',
            darkItemHoverColor: '#bbb',
            darkItemHoverBg: '#33AADD77',
            darkItemDisabledColor: '#555',
            itemMarginBlock: '0',
            itemMarginInline: '20px',
            iconMarginInlineEnd: '20px',
            activeBarBorderWidth: '0',
            groupTitleColor: '#bbb',
            darkGroupTitleColor: '#bbb',
            darkSubMenuItemBg: '#373533',
            popupBg: '#373533',
        },
        Tabs: {
            itemActiveColor: '#2277BB',
            itemColor: '#777',
            itemHoverColor: '#2277BB',
            itemSelectedColor: '#555',
            cardBg: 'rgb(0,0,0,200)',
            horizontalItemPadding: '8px 20px',
        },
        Layout: {
            bodyBg: '#f5f3f0',
            headerBg: '#f5f3f0', //#f5f5f5;
            headerHeight: 40,
            headerPadding: '0 40px',
            siderBg: '#373533',
            footerBg: '#f5f3f0',
            footerPadding: '10px 0',
        },
        Modal: {
            contentBg: '#ffffff',
            headerBg: '#f5f3f0',
            footerBg: '#f5f3f0',
            titleColor: '#2277BB',
            titleFontSize: 24,
        },
    },
};
