
export const theme = {
    token: {
        colorPrimary: '#F7B01A',
        colorSecondary: '#F7B01A',
        colorSuccess: '#52c41a',
        colorWarning: '#62B01E',
        colorError: '#f5222d',
        fontFamily: 'Roboto',
        colorBorder: '#d9d9d9',
    },
    components: {
        Form: {
            verticalLabelPadding: '0',
        },
        Collapse: {
            contentPadding: '20px',
            headerPadding: '10px',
            contentBg: '#f5f3f0',
        },
        Menu: {
            itemColor: '#bbb',
            itemBg: '#373533',
            itemSelectedColor: '#62B01E',
            itemSelectedBg: '#373533',
            itemHoverColor: '#bbb',
            itemHoverBg: '#62B01E77',
            itemDisabledColor: '#555',
            darkItemColor: '#bbb',
            darkItemBg: '#373533',
            darkItemSelectedColor: '#62B01E',
            darkItemSelectedBg: '#373533',
            darkItemHoverColor: '#bbb',
            darkItemHoverBg: '#62B01E77',
            darkItemDisabledColor: '#555',
            itemMarginBlock: '0',
            itemMarginInline: '20px',
            itemPaddingInline: '10px',
            iconMarginInlineEnd: '5px',
            activeBarBorderWidth: '0',
            groupTitleColor: '#bbb',
            darkGroupTitleColor: '#bbb',
            darkSubMenuItemBg: '#373533',
            popupBg: '#373533',
            motion: 'false',
        },
        Tabs: {
            itemActiveColor: '#F7B01A',
            itemColor: '#777',
            itemHoverColor: '#F7B01A',
            itemSelectedColor: '#555',
            cardBg: 'rgb(0,0,0,200)',
            horizontalItemPadding: '8px 20px',
        },
        Layout: {
            bodyBg: '#f5f3f0',
            headerBg: '#f5f3f0', //#f5f5f5;
            headerHeight: 40,
            headerPadding: '0 40px',
            siderBg: '#373533',
            footerBg: '#f5f3f0',
            footerPadding: '10px 0',
        },
        Modal: {
            contentBg: '#ffffff',
            headerBg: '#f5f3f0',
            footerBg: '#f5f3f0',
            titleColor: '#F7B01A',
            titleFontSize: 24,
        },
    },
};