export const ActionEmploye = {
    UcConsulterConge: {
        GO_TO_PAGE_CONSULTER_EMPLOYE: 'UcConsulterConge.action.goToPageConsulterEmploye',
        MODIFIER_CONGE: 'UcConsulterConge.action.modifierConge',
        RECUPERER_CONGE_PAR_ID: 'UcConsulterConge.action.recupererCongeParId',
        RETOUR_LISTE_CONGE: 'UcConsulterConge.action.retourListeConge',
        SUPPRIMER_CONGE: 'UcConsulterConge.action.supprimerConge',
    },
    UcConsulterEmploye: {
        AJOUTER_CONGE: 'UcConsulterEmploye.action.ajouterConge',
        GO_TO_PAGE_CONSULTER_CONGE: 'UcConsulterEmploye.action.goToPageConsulterConge',
        GO_TO_PAGE_FILTRER_EMPLOYE: 'UcConsulterEmploye.action.goToPageFiltrerEmploye',
        LISTER_CONGE_PAR_ID_EMPLOYE: 'UcConsulterEmploye.action.listerCongeParIdEmploye',
        MODIFIER_EMPLOYE: 'UcConsulterEmploye.action.modifierEmploye',
        RECUPERER_EMPLOYE_PAR_ID: 'UcConsulterEmploye.action.recupererEmployeParId',
        RETOUR_LISTE_EMPLOYE: 'UcConsulterEmploye.action.retourListeEmploye',
        SUPPRIMER_EMPLOYE: 'UcConsulterEmploye.action.supprimerEmploye',
    },
    UcCreerConge: {
        CREER_CONGE: 'UcCreerConge.action.creerConge',
        GO_TO_PAGE_CONSULTER_CONGE: 'UcCreerConge.action.goToPageConsulterConge',
        RETOUR_LISTE_CONGE: 'UcCreerConge.action.retourListeConge',
    },
    UcCreerEmploye: {
        CREER_EMPLOYE: 'UcCreerEmploye.action.creerEmploye',
        GO_TO_PAGE_CONSULTER_EMPLOYE: 'UcCreerEmploye.action.goToPageConsulterEmploye',
        RETOUR_LISTE_EMPLOYE: 'UcCreerEmploye.action.retourListeEmploye',
    },
    UcFiltrerEmploye: {
        AJOUTER_EMPLOYE: 'UcFiltrerEmploye.action.ajouterEmploye',
        APPLIQUER_FILTRE_EMPLOYE: 'UcFiltrerEmploye.action.appliquerFiltreEmploye',
        CHANGER_PAGE_FILTRER_EMPLOYE: 'UcFiltrerEmploye.action.changerPageFiltrerEmploye',
        FILTRER_EMPLOYE: 'UcFiltrerEmploye.action.filtrerEmploye',
        GO_TO_PAGE_CONSULTER_EMPLOYE: 'UcFiltrerEmploye.action.goToPageConsulterEmploye',
        INITIALISER_FILTRE_EMPLOYE: 'UcFiltrerEmploye.action.initialiserFiltreEmploye',
        INITIALISER_FILTRER_EMPLOYE: 'UcFiltrerEmploye.action.initialiserFiltrerEmploye',
    },
    UcModifierConge: {
        GO_TO_PAGE_CONSULTER_CONGE: 'UcModifierConge.action.goToPageConsulterConge',
        INIT_MODIFICATION_CONGE: 'UcModifierConge.action.initModificationConge',
        MAJ_CONGE: 'UcModifierConge.action.majConge',
        RECUPERER_CONGE_PAR_ID: 'UcModifierConge.action.recupererCongeParId',
        RETOUR_CONSULTER_CONGE: 'UcModifierConge.action.retourConsulterConge',
    },
    UcModifierEmploye: {
        GO_TO_PAGE_CONSULTER_EMPLOYE: 'UcModifierEmploye.action.goToPageConsulterEmploye',
        INIT_MODIFICATION_EMPLOYE: 'UcModifierEmploye.action.initModificationEmploye',
        MAJ_EMPLOYE: 'UcModifierEmploye.action.majEmploye',
        RECUPERER_EMPLOYE_PAR_ID: 'UcModifierEmploye.action.recupererEmployeParId',
        RETOUR_CONSULTER_EMPLOYE: 'UcModifierEmploye.action.retourConsulterEmploye',
    },
};